<?php
$_template = 'dashboard';
?>
<br />
<form action="/tipo_produto/insert" method="post">
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" class="form-control" name="nome" placeholder="Nome do Tipo do Produto">
  </div>
  <div class="form-group">
    <label for="nome">Nome no Plural</label>
    <input type="text" class="form-control" name="nome_plural" placeholder="Nome do Tipo do Produto no Plural">
  </div>
  <button type="submit" class="btn btn-success">Salvar</button>
</form>