<?php
$_template = 'dashboard';
?>
<br />
<form action="/tipo_produto/update" method="post">
  <input type="hidden" name="id" value="<?= $tipo_produto['id'] ?>" />
  <div class="form-group">
    <label for="nome">Nome</label>
    <input type="text" class="form-control" name="nome" value="<?= $tipo_produto['nome'] ?>" placeholder="Nome do Tipo do Produto">
  </div>
  <div class="form-group">
    <label for="nome">Nome no Plural</label>
    <input type="text" class="form-control" name="nome_plural" value="<?= $tipo_produto['nome_plural'] ?>" placeholder="Nome do Tipo do Produto no Plural">
  </div>
  <button type="submit" class="btn btn-success">Salvar</button>
</form>