image: gitpod/workspace-mysql
#image:
#  file: .gitpod.Dockerfile

tasks:
    - init: set echo off; mysql -u root -e "CREATE DATABASE applicationdb"; mysql -u root applicationdb < ./assets/sql/schema.mysql.sql; mysql -u root applicationdb < ./assets/sql/initdb.mysql.sql; set echo on;