<div class="container" style="text-align:justify">
    <h3>Enviar Pedido</h3>
    <form action="/pedido/enviar" method="post">
        <div class="form-group">
            <label for="cliente">Nome</label>
            <input type="text" class="form-control" name="cliente" required>
        </div>
        <div class="form-group">
            <label for="email">E-Mail</label>
            <input type="email" class="form-control" name="email" required>
        </div>
        <div class="form-group">
            <label for="telefone">Telefone</label>
            <input type="text" class="form-control" name="telefone" placeholder="(00) 0000-0000" required>
        </div>
        <div class="form-group">
            <label for="endereco">Endereço para Entrega</label>
            <input type="text" class="form-control" name="endereco" placeholder="Nome da Rua/Avenida, número, bairro" required>
        </div>
        <div class="form-group">
            <label for="telefone">Pedido</label>
            <pre><?= $pedido ?></pre>
            <input type="hidden" name="pedido" value="<?= $pedido ?>" />
        </div>
        <div class="form-group">
            <label for="observacoes">Informações Adicionais (Opcional)</label>
            <input type="text" class="form-control" name="observacoes" placeholder="Informações Adicionais" />
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
</div>