<?php
$subtotal = [];
?>

<div class="container">
    <div class="card mt-5">
       <div class="card-body">
          <h4 class="card-title">Pedido</h4>
          <a href="/page/cardapio">Lista de Produtos</a>
        </div>
    </div>
    <form action="/pedido/update" method="post">
        <table class="table table-strip">
            <thead>
                <tr>
                    <th>Produto</th>
                    <th>Quantidade</th>
                    <th>Preço</th>
                    <th>Subtotal</th>
                    <th>&nbsp;</th>

                </tr>       
            </thead>
            <tbody>
                <?php foreach($itens_pedido as $k => $i): ?>
                <tr>
                    <td><?= $i['nome'] ?></td>
                    <td><input type="number" name="prod_qtd__<?= $k ?>" value="<?= $i['quantidade'] ?>" /></td>
                    <td>R$ <?= $i['preco'] ?></td>
                    <td>R$ <?php $subtotal[$k] = $i['preco'] * $i['quantidade']; echo number_format($subtotal[$k], 2, ',', '.') ?></td>
                    <td>
                        <a href="/pedido/removeitem/<?= $k ?>" class="btn btn-danger">Remover</a>
                    </td>
                </tr>
                <?php endforeach; ?>
                <tr>
                    <td colspan="3" class="text-right"><b>Total: </b></td>
                    <td>R$<?= number_format(array_sum($subtotal), 2, ',', '.')?></td>
                    <td></td>
                </tr>
            </tbody>
        </table>
        <?php if(count($itens_pedido) > 0): ?>
        <a class="btn btn-info" href="<?= url('page/cardapio') ?>">Continuar comprando</a>
        <button class="btn btn-primary" type="submit">Atualizar Carrinho</button>
        <a class="btn btn-info" href="<?= url('/pedido/fechar') ?>">Realizar Pedido</a>
        <?php endif ?>
    </form>
</div>

<br />