
<!DOCTYPE html>
  <head>
    <title>Home</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/assets/css/bootstrap.css">
    <link rel="stylesheet" href="/assets/css/fonts.css">
    <link rel="stylesheet" href="/assets/css/default.css">
    <link rel="icon" href="/assets/images/icon.ico" type="image/x-icon">
  </head>
  <body>
    <div class="page">
          <div class="preloader">
    </div>
        <!-- MENU E SLIDERS CONFIG-->
        <div class="rd-navbar-wrap">
          <nav class="rd-navbar rd-navbar-modern" data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed" data-md-device-layout="rd-navbar-fixed" data-lg-layout="rd-navbar-static" data-lg-device-layout="rd-navbar-fixed" data-xl-layout="rd-navbar-static" data-xl-device-layout="rd-navbar-static" data-xxl-layout="rd-navbar-static" data-xxl-device-layout="rd-navbar-static" data-lg-stick-up-offset="56px" data-xl-stick-up-offset="56px" data-xxl-stick-up-offset="56px" data-lg-stick-up="true" data-xl-stick-up="true" data-xxl-stick-up="true">
            <div class="rd-navbar-inner-outer">
              <div class="rd-navbar-inner">
                <!-- MENU E SLIDERS DO PAINEL BRANCO-->
                <div class="rd-navbar-panel">
                  <!-- CONTATOS MENUS + LOGO-->
                  <div class="rd-navbar-brand"><a class="brand" href="/"><img class="brand-logo-dark" src="/assets/images/logo-198x66.png" alt="" width="198" height="66"/></a></div>
                </div>
                <div class="rd-navbar-right rd-navbar-nav-wrap">
                  <div class="rd-navbar-aside">
                    <ul class="rd-navbar-contacts-2">
                      <li>
                        <div class="unit unit-spacing-xs">
                          <div class="unit-left"><span class="icon mdi mdi-phone"></span></div>
                          <div class="unit-body"><a class="phone">18 996803394</a></div>
                        </div>
                      </li>
                      <li>
                        <div class="unit unit-spacing-xs">
                          <div class="unit-left"><span class="icon mdi mdi-map-marker"></span></div>
                          <div class="unit-body"><a class="address">Rua Sete Setembro, 76, Centro</a></div>
                        </div>
                      </li>
                    </ul>
                    <ul class="list-share-2">
                      <li><a class="icon mdi mdi-facebook" href="#"></a></li>
                      <li><a class="icon mdi mdi-twitter" href="#"></a></li>
                      <li><a class="icon mdi mdi-instagram" href="#"></a></li>
                    </ul>
                  </div>
                  <div class="rd-navbar-main">
                    <!-- MENUS e + CONFIG-->
                    <ul class="rd-navbar-nav">
                      <li class="rd-nav-item active"><a class="rd-nav-link" href="/">Home</a>
                      </li>
                      <li class="rd-nav-item"><a class="rd-nav-link" href="/page/cardapio">Cardápio</a>
                      </li>
                      <li class="rd-nav-item"><a class="rd-nav-link" href="/page/sobre">Sobre</a>
                      </li>
                        <li class="rd-nav-item"><a class="rd-nav-link" href="/page/pedidos">Pedidos</a>
                      </li>
                      <li class="rd-nav-item"><a class="rd-nav-link" href="/page/localizacao">Localização</a>

                      <li class="rd-nav-item"><a class="rd-nav-link" href="/admin/dashboard">Admin</a>

                    </ul>
                    </ul>
                    </ul>
                  </div>
                </div>
                <div class="rd-navbar-project-hamburger rd-navbar-project-hamburger-open rd-navbar-fixed-element-1" data-multitoggle=".rd-navbar-inner" data-multitoggle-blur=".rd-navbar-wrap" data-multitoggle-isolate="data-multitoggle-isolate">
                  <div class="project-hamburger"><span class="project-hamburger-arrow"></span><span class="project-hamburger-arrow"></span><span class="project-hamburger-arrow"></span>
                  </div>
                </div>
                <div class="rd-navbar-project">
                  <div class="rd-navbar-project-header">
                    <div class="rd-navbar-project-hamburger rd-navbar-project-hamburger-close" data-multitoggle=".rd-navbar-inner" data-multitoggle-blur=".rd-navbar-wrap" data-multitoggle-isolate="data-multitoggle-isolate">
                    </div>
                  </div>
                  <div class="rd-navbar-project-content rd-navbar-content">
                    <div>
                      <div class="row gutters-20" data-lightgallery="group">
                        <div class="col-6">
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </nav>
        </div>
      
      
      <?= $_contents ?>

      <footer class="section footer-modern context-dark footer-modern-2">
        <div class="footer-modern-line">
          <div class="container">
            <div class="row row-50">
              <div class="col-md-6 col-lg-4">
                <h5 class="footer-modern-title oh-desktop"><span class="d-inline-block wow slideInLeft">Escolha o seu.</span></h5>
                <ul class="footer-modern-list d-inline-block d-sm-block wow fadeInUp">
                  <li><a href="#">X TUDO</a></li>
                  <li><a href="#">X BACON</a></li>
                  <li><a href="#">X SALADA</a></li>
                  <li><a href="#">TRIPLO X</a></li>
                  <li><a href="#">BIG DO DIA</a></li>
                  <li><a href="#">HOT DOG</a></li>
                </ul>
              </div>
              <div class="col-md-6 col-lg-4 col-xl-3">
                <h5 class="footer-modern-title oh-desktop"><span class="d-inline-block wow slideInLeft">Patrocinadores</span></h5>
                <ul class="footer-modern-list d-inline-block d-sm-block wow fadeInUp">
                  <li><a href="about-us.html">Conquista</a></li>
                  <li><a href="#">Conti</a></li>
                  <li><a href="#">Choperia Meetz</a></li>
                  <li><a href="#">Dubs</a></li>
                  <li><a href="#">Armazem Biazon</a></li>
                  <li><a href="contacts.html">Otica Pietro</a></li>
                </ul>
              </div>
              <div class="col-lg-4 col-xl-5">
                <h5 class="footer-modern-title oh-desktop"><span class="d-inline-block wow slideInLeft">E-mail: gm995050@gmail.com</span></h5>
                
    <!-- Javascript-->
    <script src="/assets/js/core.min.js"></script>
    <script src="/assets/js/script.js"></script>
	
  </body>
</html>