<section class="section section-md bg-default">
    <div class="tab-content tab-content-1">
    <div class="tab-pane fade show active" id="tabs-4-1">
        <h4>Sobre</h4>

        <p>O Projeto "Food's Delivery", foi criado no ano de 2020 por um grupo de 5 estudantes da Etec, pois queriamos facilitar vendas e controle de proprietários do estabelecimento, e assim facilitando o atendimento aos clientes, além de manter o estabelecimento informatizado de tudo, e facilitando também as entregas das encomendas, e o controle financeiro, o site seria focado em lanchonetes, o objetivo dele basicamente é solucionar um problema em relação aos pedidos online, onde o cliente iria acessar o site e fazer o seu pedido baseado em i-food, e claro esse projeto foi criado para se adaptar a qualquer restaurante, lanchonete, ou outros ligado a esse meio.</p>

        <img src="/assets/images/logo-198x66.png" alt="" width="335" height="158"/>
    </div>
</div>
</div>
</section>